# Generated by Django 2.2.5 on 2019-09-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_hash', models.CharField(max_length=36)),
                ('offer_value', models.FloatField()),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
